import {Assets} from 'react-native-ui-lib';
Assets.loadAssetsGroup('icons', {
  buy: require('../assets/icons/cart_icon.png'),
  checkmark: require('../assets/icons/tick.png'),
  cupActive: require('../assets/icons/cup_active.png'),
  cupInActive: require('../assets/icons/cup_inactive.png'),
  gift: require('../assets/icons/gift_icon.png'),
  icArrowRight: require('../assets/icons/next_icon.png'),
  icArrowLeft: require('../assets/icons/back_icon.png'),
  iconEmail: require('../assets/icons/message_icon.png'),
  iconEye: require('../assets/icons/show_pwd_icon.png'),
  iconLock: require('../assets/icons/Lock_icon.png'),
  iconPhone: require('../assets/icons/smf_icon.png'),
  iconProfile: require('../assets/icons/man_icon.png'),
  iconRight: require('../assets/icons/rightArrowShort.png'),
  iconStore: require('../assets/icons/store_icon.png'),
  order: require('../assets/icons/cart_icon.png'),
  profile: require('../assets/icons/profile_icon.png'),
  right: require('../assets/icons/rightArrowShort.png'),
  selectActive: require('../assets/icons/selectedDot.png'),
  selectInActive: require('../assets/icons/unselectedDot.png'),
  smaillcup: require('../assets/icons/s_volume_icon.png'),
  smalllocation: require('../assets/icons/location.png'),
  store: require('../assets/icons/store_icon.png'),
  wallet: require('../assets/icons/card.png'),
});
